providers = ["node"]

[nixpacks]
version = "0.1"
channel = "stable-24.05"

[dependencies.nix]
nix = ["nodejs_20", "silver-searcher"]


[phases.build]
cmds = ["npm install --prefix ./client", "npm run build --prefix ./client", "npm install --prefix ./server"]

[start]
cmd = "npm run start --prefix ./server"

[environment]
NODE_ENV = "production"
HOST = "0.0.0.0"